name: Build and distribute APK

on:
  push:
    branches:
      - develop

env:
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Android SDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Install dependencies
        run: ./gradlew build

      - name: Build APK
        run: ./gradlew assembleDebug

#      - name: Install Firebase CLI
#        run: |
#          npm install -g firebase-tools
#
#      - name: Login to Firebase
#        run: firebase login:ci --token=$FIREBASE_TOKEN --non-interactive
#
#      - name: Deploy to Firebase Distribution
#        run: firebase deploy --token=$FIREBASE_TOKEN

      - name: Distribute APK to AppCenter
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: ${{ env.APP_CENTER_APP_NAME }}
          token: ${{ secrets.APP_CENTER_API_TOKEN }}
          group: testers
          file: app/build/intermediates/apk/debug/app-debug.apk
          notifyTesters: true
          debug: true