name: Upload APK to Firebase

on:
  push:
    branches:
      - develop

env:
  FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload APK to Firebase
        run: |
          curl \
            --header "Content-Type: application/vnd.android.package-archive" \
            --header "Authorization: Bearer ${FIREBASE_API_KEY}" \
            --data-binary @app/build/outputs/apk/release/app-release.apk \
            https://appdistribution.googleapis.com/v1/apps/1:155963927208:android:aff1039ad00595b10cf09d/releases